/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lingo;

import java.util.Arrays;
import java.util.Random;

/**
 *
 * @author Asus
 */
public class GUI extends javax.swing.JPanel {

    //globālās funkcijas
        String word = "";       
        int gamesLeft = 0;
        char[] wordArray = word.toCharArray();
        char[] temporalArray = new char[5];
        
        boolean checkInput = false;
        boolean newGame = true;
        boolean repeatedGame = false;
        
        
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    public String RandomWords(){
    String[] wordsArray = new String[26];
    wordsArray[0] = "APPLE";
    wordsArray[1] = "BRAIN";
    wordsArray[2] = "CHINA";
    wordsArray[3] = "DREAM";
    wordsArray[4] = "EARTH";
    wordsArray[5] = "FAITH";
    wordsArray[6] = "GROUP";
    wordsArray[7] = "HORSE";
    wordsArray[8] = "INDEX";
    wordsArray[9] = "JOINT";
    wordsArray[10] = "LASER";
    wordsArray[11] = "INDEX";
    wordsArray[12] = "JOINT";
    wordsArray[13] = "LASER";
    wordsArray[14] = "MOVIE";
    wordsArray[15] = "NOISE";
    wordsArray[16] = "OCEAN";
    wordsArray[17] = "PAINT";
    wordsArray[18] = "QUEEN";
    wordsArray[19] = "ROYAL";
    wordsArray[20] = "SPORT";
    wordsArray[21] = "TRAIN";
    wordsArray[22] = "URBAN";
    wordsArray[23] = "VIRUS";
    wordsArray[24] = "WATER";
    wordsArray[25] = "YOUTH";
    
    Random r=new Random();
    int randomNumber=r.nextInt(wordsArray.length);
    String word = wordsArray[randomNumber];
    return word;
    
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField_1 = new javax.swing.JTextField();
        jButtonMinet = new javax.swing.JButton();
        jLabelAtbilde = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jTextField_1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jTextField_1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_1.setAutoscrolls(false);
        jTextField_1.setBorder(null);
        jTextField_1.setPreferredSize(new java.awt.Dimension(50, 50));
        jTextField_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_1ActionPerformed(evt);
            }
        });

        jButtonMinet.setBackground(new java.awt.Color(255, 204, 102));
        jButtonMinet.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButtonMinet.setText("Guess!");
        jButtonMinet.setActionCommand("");
        jButtonMinet.setBorder(null);
        jButtonMinet.setBorderPainted(false);
        jButtonMinet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinetActionPerformed(evt);
            }
        });

        jLabelAtbilde.setFont(new java.awt.Font("Roboto", 2, 11)); // NOI18N
        jLabelAtbilde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAtbilde.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);

        jLabel4.setBackground(new java.awt.Color(204, 204, 204));
        jLabel4.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);

        jLabel5.setBackground(new java.awt.Color(204, 204, 204));
        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelAtbilde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButtonMinet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTextField_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(57, 57, 57))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMinet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAtbilde, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private String checkInput(String guessedWord){
        
        if(guessedWord.matches(".*\\W+.*") || guessedWord.matches(".*\\d+.*")){ //"^[a-zA-Z0-9]+$" ".*[a-zA-Z]+.*"  ".*[0-9]+.*" ".*\\D+.*"
            checkInput = false;
            return guessedWord;
        } 
        if(guessedWord.length() != 5){
            checkInput = false;
            return guessedWord;
        } 
        else if(guessedWord.matches(".*[a-zA-Z]+.*")){
            guessedWord = guessedWord.toUpperCase();
            checkInput = true;
            return guessedWord; 
    }
        return guessedWord;   
    }
    
    private void fillLabels (int gamesLeft, int label, int R, int G, int B){
        switch (label) {
            case 0:  jLabel1.setBackground(new java.awt.Color(R, G, B));
                     break;
            case 1:  jLabel2.setBackground(new java.awt.Color(R, G, B));
                     break;
            case 2:  jLabel3.setBackground(new java.awt.Color(R, G, B));
                     break;
            case 3:  jLabel4.setBackground(new java.awt.Color(R, G, B));
                     break;
            case 4:  jLabel5.setBackground(new java.awt.Color(R, G, B));
                     break;         
        }
    }
    
    private void fillLabelsText (int gamesLeft, int label, char character){
        switch (label) {
            case 0:  jLabel1.setText("" + character);;
                     break;
            case 1:  jLabel2.setText("" + character);;
                     break;
            case 2:  jLabel3.setText("" + character);;
                     break;
            case 3:  jLabel4.setText("" + character);;
                     break;
            case 4:  jLabel5.setText("" + character);;
                     break;         
        } 
    }
    
    private void jTextField_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_1ActionPerformed

    private void jButtonMinetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinetActionPerformed
        //TODO ko darīt kad burts atkārtojas 2 reizes??
        // Initialize first game and select random word
        if(newGame==true){
            word = "APPLE";
            wordArray = word.toCharArray();
            gamesLeft = 5;
            jLabel1.setText("");
            newGame=false;
        }
        // Initialize next game
        if(repeatedGame==true){
            word = RandomWords();
            wordArray = word.toCharArray();
            gamesLeft = 5;
            jLabel1.setText("");
            jButtonMinet.setText("Guess!");
            jTextField_1.setText("");
            jLabel1.setBackground(new java.awt.Color(204,204,204));
            jLabel2.setText("");
            jLabel2.setBackground(new java.awt.Color(204,204,204));            
            jLabel3.setText("");
            jLabel3.setBackground(new java.awt.Color(204,204,204));
            jLabel4.setText("");
            jLabel4.setBackground(new java.awt.Color(204,204,204)); 
            jLabel5.setText("");
            jLabel5.setBackground(new java.awt.Color(204,204,204));
            jTextField_1.setEnabled(true);
            repeatedGame=false;
            return;
        }
        
        //Read word from field, check input
        String guessedWord = jTextField_1.getText();    
        guessedWord = checkInput(guessedWord);
        
        
        if(checkInput==true && gamesLeft >1){
            gamesLeft = gamesLeft -1; //every time when button is clicked, reduce by remaining clicks by one 
            jLabelAtbilde.setText("");
            char[] guessedWordArray = guessedWord.toCharArray(); // Create array wrom guessed word
            for(int i=0; i<5; i++){
                temporalArray[i] = 0;
                }
                    
            // Step 1, mark all labels as incorrect
            jLabel1.setText("" + guessedWordArray[0]);
            jLabel1.setBackground(new java.awt.Color(255,51,51));
            jLabel2.setText("" + guessedWordArray[1]);
            jLabel2.setBackground(new java.awt.Color(255,51,51));            
            jLabel3.setText("" + guessedWordArray[2]);
            jLabel3.setBackground(new java.awt.Color(255,51,51));
            jLabel4.setText("" + guessedWordArray[3]);
            jLabel4.setBackground(new java.awt.Color(255,51,51)); 
            jLabel5.setText("" + guessedWordArray[4]);
            jLabel5.setBackground(new java.awt.Color(255,51,51));
            
            // Step 1.2, create array of letters with correct place, so see if they will repeat
            if(guessedWordArray[0] == wordArray[0]){
                temporalArray[0] = guessedWordArray[0];
                }
            if(guessedWordArray[1] == wordArray[1]){
                temporalArray[1] = guessedWordArray[1];
                }
            if(guessedWordArray[2] == wordArray[2]){
                temporalArray[2] = guessedWordArray[2];
                }
            if(guessedWordArray[3] == wordArray[3]){
                temporalArray[3] = guessedWordArray[3];
                }
            if(guessedWordArray[4] == wordArray[4]){
                temporalArray[4] = guessedWordArray[4];
                } 
            
            // Step 2, mark labels that have correct letter (ignore place)
            for(int i=0; i<5; i++){
                for(int j=0; j<5; j++){
                    if(guessedWordArray[i] == wordArray[j]){
                        if(guessedWordArray[0] == temporalArray[0]){
                            temporalArray[0] = 0;
                        }
                        else if (guessedWordArray[0] == wordArray[j]){
                            jLabel2.setBackground(new java.awt.Color(255,204,102)); 
                        }
                        if(guessedWordArray[1] == temporalArray[1]){
                            temporalArray[1] = 0;
                        }
                        else if (guessedWordArray[1] == wordArray[j]){
                            jLabel2.setBackground(new java.awt.Color(255,204,102)); 
                        }
                        if(guessedWordArray[2] == temporalArray[2]){
                            temporalArray[2] = 0;
                        }
                        else if (guessedWordArray[2] == wordArray[j]){
                            jLabel2.setBackground(new java.awt.Color(255,204,102)); 
                        }
                        if(guessedWordArray[3] == temporalArray[3]){
                            temporalArray[3] = 0;
                        }
                        else if (guessedWordArray[3] == wordArray[j]){
                            jLabel2.setBackground(new java.awt.Color(255,204,102)); 
                        }         
                        if(guessedWordArray[4] == temporalArray[4]){
                            temporalArray[4] = 0;
                        }
                        else if (guessedWordArray[4] == wordArray[j]){
                            jLabel2.setBackground(new java.awt.Color(255,204,102)); 
                        }                             
                    }
                }

                //Step 3, mark all labels that have correct letter and place
                if(guessedWordArray[0] == wordArray[0]){
                    jLabel1.setBackground(new java.awt.Color(153,255,102));
                    }
                if(guessedWordArray[1] == wordArray[1]){
                    jLabel2.setBackground(new java.awt.Color(153,255,102));
                    }
                if(guessedWordArray[2] == wordArray[2]){
                    jLabel3.setBackground(new java.awt.Color(153,255,102));
                    }
                if(guessedWordArray[3] == wordArray[3]){
                    jLabel4.setBackground(new java.awt.Color(153,255,102));
                    }
                if(guessedWordArray[4] == wordArray[4]){
                    jLabel5.setBackground(new java.awt.Color(153,255,102));
                    } 
            }
            if(Arrays.equals(guessedWordArray, wordArray)){
                jLabelAtbilde.setText("Congratulations, you win!");
                gamesLeft = 5;
                repeatedGame=true;
                jTextField_1.setEnabled(false);
                jButtonMinet.setText("Start New Game!");
                return;
            }
        

        jLabelAtbilde.setText(gamesLeft + " attempts left!");  
        }
        else if (checkInput==false && gamesLeft >1){
            jLabelAtbilde.setText("The word must consist of five letters");            
        }
        
        else{
            jTextField_1.setText(word);
            jLabelAtbilde.setText("Game over, you lost");
            gamesLeft = 5;
            repeatedGame=true;
            jTextField_1.setEnabled(false);
            jButtonMinet.setText("Start New Game!");
            return;
        }
        
    }//GEN-LAST:event_jButtonMinetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMinet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAtbilde;
    private javax.swing.JTextField jTextField_1;
    // End of variables declaration//GEN-END:variables
}
